#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.4 on Fri Aug  5 22:41:56 2022
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MainFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MainFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((640, 480))
        self.SetTitle("English Learning...")

        self.frame_statusbar = self.CreateStatusBar(6)
        self.frame_statusbar.SetStatusWidths([10, 120, 120, 120, 120, 120])
        # statusbar fields
        frame_statusbar_fields = ["", "all words: 12345", "success: 12345", "errors: 12345", "percents: 100%", "iterations: 99"]
        for i in range(len(frame_statusbar_fields)):
            self.frame_statusbar.SetStatusText(frame_statusbar_fields[i], i)

        # Tool Bar
        self.frame_toolbar = wx.ToolBar(self, -1, style=wx.TB_NOICONS | wx.TB_TEXT)
        self.frame_toolbar.AddTool(wx.ID_ANY, "Check", wx.Bitmap(16, 16), wx.NullBitmap, wx.ITEM_NORMAL, "", "")
        self.frame_toolbar.AddTool(wx.ID_ANY, "Reset", wx.Bitmap(16, 16), wx.NullBitmap, wx.ITEM_NORMAL, "", "")
        self.SetToolBar(self.frame_toolbar)
        self.frame_toolbar.Realize()
        # Tool Bar end

        self.panel = wx.ScrolledWindow(self, wx.ID_ANY, style=wx.TAB_TRAVERSAL)
        self.panel.SetScrollRate(0, 50)

        self.sizer = wx.BoxSizer(wx.VERTICAL)

        self.panel.SetSizer(self.sizer)

        self.Layout()
        self.Centre()
        # end wxGlade

# end of class MainFrame

class MainWindow(wx.App):
    def OnInit(self):
        self.frame = MainFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MainWindow
